Simple Social Media/Controllers/ChatController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Simple_Social_Media.BLL.DTO;
using Simple_Social_Media.BLL.Interfaces;
using Simple_Social_Media.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Simple_Social_Media.Controllers
{
    [Authorize(Roles ="User")]
    public class ChatController : Controller
    {
        IChatService chatService;

        public ChatController(IChatService service)
        {
            chatService = service;
        }

        private IUserService UserService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        private string currentId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            UserDTO currentUser = await UserService.GetByIdAsync(currentId);
            if (currentUser == null)
            {
                return RedirectToAction("SignOut");
            }
            else
            {
                currentUser.Id = currentId;
                UserChatsViewModel userChats = new UserChatsViewModel();
                
                userChats.Chats = await chatService.GetAllUserChats(currentId);
                userChats.UserName = currentUser.UserName;

                userChats.UserProfile = new UserProfileViewModel()
                {
                    UserId=currentId,
                    UserName=currentUser.UserName,
                    Birthday=currentUser.Birthday,
                    Status=currentUser.Status,
                    Email=currentUser.Email,
                    Phone=currentUser.PhoneNumber,
                };


                return View(userChats);
            }
        }

        [HttpGet]
        public async Task<ActionResult> ChatWithMessages(int id)
        {

            ChatDTO chat = await chatService.GetChat(new ChatDTO { ChatId = id });

            ChatViewModel chatView = new ChatViewModel
            {
                ChatId = id,
                UserId = currentId,
                FriendName = chat.FriendName,
                Messages = await chatService.GetMessagesAsync(id),
            };
            chatView.NewMessage = chatView.Messages.LastOrDefault().Text;

            return PartialView(chatView);
        }


        public async Task<ActionResult> SignOut()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            await Task.Run(()=>authenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie));
            return RedirectToAction("Index", "Home");
        }
    }
}

Simple Social Media/Controllers/FriendsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Simple_Social_Media.BLL.DTO;
using Simple_Social_Media.BLL.Interfaces;
using Simple_Social_Media.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Simple_Social_Media.Controllers
{
    [Authorize(Roles ="User")]
    public class FriendsController : Controller
    {

        private readonly IContactService contactService;

        private string UserID
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        private IUserService UserService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        public FriendsController(IContactService contactService)
        {
            this.contactService = contactService;
        }


        [HttpGet]
        public async Task<ActionResult> GetFriends()
        {
            UserDTO user = await UserService.GetByIdAsync(UserID);
            FriendsViewModel friends = new FriendsViewModel();
            friends.UserProfileModel = new UserProfileViewModel
            {
                UserName = user.UserName,
                Status = user.Status,
                Phone = user.PhoneNumber,
                Birthday = user.Birthday,
                Email = user.Email,
                UserId = user.Id,
            };
            try
            {
                friends.Contacts = await contactService.GetFriendsAsync(UserID);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            return View(friends) ;
        }

        [HttpPost]
        public async Task<ActionResult> AddFriend(string id)
        {
            ContactDTO contact = new ContactDTO
            {
                User = UserID,
                Friend = id,
                IsDeleted = false,
            };
            await contactService.CreateAsync(contact);
            return RedirectToAction("GetFriends");
        }

        
        public async Task<ActionResult> FindAccounts(FriendSearchViewModel friendSearch)
        {
            UserDTO filters = new UserDTO
            {
                Id=UserID,
                UserName=friendSearch.Name,
                Email=friendSearch.Email,
                PhoneNumber=friendSearch.Phone,
            };
            friendSearch.SearchedUsers = await UserService.FindUsers(filters);

            return PartialView("PrintFriendsPartial", friendSearch);
        }

       

        [HttpPost]
        public async Task<ActionResult> DeleteFromFriends(int id)
        {
            await contactService.DeleteByIdAsync(id);
            return RedirectToAction("GetFriends");
        }

        
    }
}

Simple Social Media/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a href="#" class="navbar-brand">
                <img src="~/Images/logo.png" width="45" alt="logo" class="d-inline-block align-middle">
                <span class="text-uppercase font-weight-bold">Circle NetWork</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
                    aria-controls="navbarContent" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Управление", "Index", "Admin", null, new { @class = "nav-link" })</li>
                </ul>

            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <footer class="footer fixed-bottom bg-info">
        <div class="text-center p-3 text-dark">
            <p>© 2021 Copyright: Kapustianskyi Danylo</p>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Simple Social Media/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a href="#" class="navbar-brand">
                <img src="~/Images/logo.png" width="45" alt="logo" class="d-inline-block align-middle">
                <span class="text-uppercase font-weight-bold">Circle NetWork</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
                    aria-controls="navbarContent" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Домашняя страница", "Index", "Home",null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Чаты", "Index", "Chat",null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Друзья", "GetFriends", "Friends",null, new { @class = "nav-link" })</li>
                </ul>

            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
        <footer class="footer fixed-bottom bg-info">
            <div class="text-center p-3 text-dark">
                <p>© 2021 Copyright: Kapustianskyi Danylo</p>
            </div>
        </footer>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>